sudo: required
services:
  - docker

before_install:
  - docker build -t shakenbake89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shakenbake89/docker-react npm run test
